name: Test pnpm with cached modules

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Self pnpm with cached modules should be able to run
        uses: ./pnpm-with-cached-modules
        id: pnpm-with-cached-modules
        with:
          project_path: ./pnpm-with-cached-modules
